// Package server movies_handler.go provides admin HTTP handlers for the
// movies demo: vector search, notes embedding persistence, and the BYOK
// vault-secret key override lifecycle. SSE chat streaming lives in
// movies_chat.go; BYOK helpers and handlers live in movies_byok.go.
package server

import (
	"net/http"
	"regexp"
	"strings"
	"unicode/utf8"

	"github.com/allyourbase/ayb/internal/ai"
	"github.com/allyourbase/ayb/internal/httputil"
	"github.com/allyourbase/ayb/internal/vector"
)

const (
	moviesSearchDefaultLimit = 10
	moviesSearchMaxLimit     = 50
	moviesNoteMaxLength      = 2000

	// Stage 2's deterministic embedding pipeline writes VECTOR(3) into
	// movies.embedding and movies_notes.embedding. moviesEmbeddingDim must
	// match that schema dimension; longer embeddings are truncated and
	// shorter ones are zero-padded so any AI provider's output can be
	// persisted without altering the schema.
	moviesEmbeddingDim = 3

	serviceUnavailableMovies = "movies demo backend is not enabled"
)

// movieSlugRE constrains slug values to the same kebab-case shape used by
// examples/movies/seed.sql. The FK on movies_notes(movie_slug) ultimately
// rejects unknown slugs, but rejecting invalid shapes here keeps obviously
// bad input from reaching the database.
var movieSlugRE = regexp.MustCompile(`^[a-z0-9][a-z0-9\-]{0,127}$`)

type moviesSearchRequest struct {
	Query string `json:"query"`
	Limit int    `json:"limit,omitempty"`
}

type moviesSearchRow struct {
	Slug        string  `json:"slug"`
	Title       string  `json:"title"`
	Overview    string  `json:"overview"`
	ReleaseYear int     `json:"release_year"`
	Similarity  float64 `json:"similarity"`
}

type moviesSearchResponse struct {
	Rows []moviesSearchRow `json:"rows"`
}

type moviesNotesEmbedRequest struct {
	Text      string `json:"text"`
	MovieSlug string `json:"movie_slug"`
}

type moviesNotesEmbedResponse struct {
	ID        string    `json:"id"`
	MovieSlug string    `json:"movie_slug"`
	Embedding []float64 `json:"embedding"`
}

// handleMoviesSearch executes the movies search RPC with a query embedding
// generated by the configured EmbeddingProvider. Validation order matters:
// body parsing → input bounds → backing-service availability. The 503 path
// is only reached after validated inputs so callers get consistent error
// shapes regardless of demo wiring state.
func (s *Server) handleMoviesSearch(w http.ResponseWriter, r *http.Request) {
	var body moviesSearchRequest
	if !httputil.DecodeJSON(w, r, &body) {
		return
	}
	query := strings.TrimSpace(body.Query)
	if query == "" {
		httputil.WriteError(w, http.StatusBadRequest, "query is required")
		return
	}
	limit := body.Limit
	if limit == 0 {
		limit = moviesSearchDefaultLimit
	}
	if limit < 1 || limit > moviesSearchMaxLimit {
		httputil.WriteError(w, http.StatusBadRequest, "limit must be between 1 and 50")
		return
	}

	if s.pool == nil || s.aiRegistry == nil {
		serviceUnavailable(w, serviceUnavailableMovies)
		return
	}
	ep, model, ok := s.resolveMoviesEmbeddingProvider()
	if !ok {
		serviceUnavailable(w, serviceUnavailableMovies)
		return
	}

	embResp, err := ep.GenerateEmbedding(r.Context(), ai.EmbeddingRequest{Model: model, Input: []string{query}})
	if err != nil {
		httputil.WriteError(w, http.StatusBadGateway, "embedding generation failed: "+err.Error())
		return
	}
	if len(embResp.Embeddings) == 0 {
		httputil.WriteError(w, http.StatusBadGateway, "embedding provider returned no vectors")
		return
	}
	embedding := fitEmbedding(embResp.Embeddings[0], moviesEmbeddingDim)

	rows, err := s.pool.Query(r.Context(),
		`SELECT slug, title, overview, release_year, similarity FROM search_movies($1, $2, $3)`,
		query, vector.FormatVectorLiteral(embedding), limit,
	)
	if err != nil {
		httputil.WriteError(w, http.StatusInternalServerError, "search query failed")
		return
	}
	defer rows.Close()

	out := moviesSearchResponse{Rows: []moviesSearchRow{}}
	for rows.Next() {
		var row moviesSearchRow
		if err := rows.Scan(&row.Slug, &row.Title, &row.Overview, &row.ReleaseYear, &row.Similarity); err != nil {
			httputil.WriteError(w, http.StatusInternalServerError, "search row scan failed")
			return
		}
		out.Rows = append(out.Rows, row)
	}
	if err := rows.Err(); err != nil {
		httputil.WriteError(w, http.StatusInternalServerError, "search iteration failed")
		return
	}
	httputil.WriteJSON(w, http.StatusOK, out)
}

// handleMoviesNotesEmbed embeds a user-supplied note for a given movie and
// persists it into movies_notes. The FK on movie_slug surfaces unknown-slug
// errors as a 404 from the database layer; we map common pg errors to user-
// facing statuses inline.
func (s *Server) handleMoviesNotesEmbed(w http.ResponseWriter, r *http.Request) {
	var body moviesNotesEmbedRequest
	if !httputil.DecodeJSON(w, r, &body) {
		return
	}
	text := strings.TrimSpace(body.Text)
	if text == "" {
		httputil.WriteError(w, http.StatusBadRequest, "text is required")
		return
	}
	if utf8.RuneCountInString(text) > moviesNoteMaxLength {
		httputil.WriteError(w, http.StatusBadRequest, "text must be at most 2000 characters")
		return
	}
	slug := strings.TrimSpace(body.MovieSlug)
	if slug == "" {
		httputil.WriteError(w, http.StatusBadRequest, "movie_slug is required")
		return
	}
	if !movieSlugRE.MatchString(slug) {
		httputil.WriteError(w, http.StatusBadRequest, "movie_slug is invalid")
		return
	}

	if s.pool == nil || s.aiRegistry == nil {
		serviceUnavailable(w, serviceUnavailableMovies)
		return
	}
	ep, model, ok := s.resolveMoviesEmbeddingProvider()
	if !ok {
		serviceUnavailable(w, serviceUnavailableMovies)
		return
	}

	embResp, err := ep.GenerateEmbedding(r.Context(), ai.EmbeddingRequest{Model: model, Input: []string{text}})
	if err != nil {
		httputil.WriteError(w, http.StatusBadGateway, "embedding generation failed: "+err.Error())
		return
	}
	if len(embResp.Embeddings) == 0 {
		httputil.WriteError(w, http.StatusBadGateway, "embedding provider returned no vectors")
		return
	}
	embedding := fitEmbedding(embResp.Embeddings[0], moviesEmbeddingDim)

	var id string
	err = s.pool.QueryRow(r.Context(),
		`INSERT INTO movies_notes (id, movie_slug, text, embedding)
		 VALUES (gen_random_uuid(), $1, $2, $3)
		 RETURNING id`,
		slug, text, vector.FormatVectorLiteral(embedding),
	).Scan(&id)
	if err != nil {
		// FK violation surfaces here when the movie does not exist; map to
		// 404 with a clear message rather than leaking the raw pg error.
		if strings.Contains(err.Error(), "foreign key") {
			httputil.WriteError(w, http.StatusNotFound, "movie not found for slug "+slug)
			return
		}
		httputil.WriteError(w, http.StatusInternalServerError, "note insert failed")
		return
	}
	httputil.WriteJSON(w, http.StatusOK, moviesNotesEmbedResponse{
		ID:        id,
		MovieSlug: slug,
		Embedding: embedding,
	})
}

// resolveMoviesEmbeddingProvider returns the configured embedding-capable
// provider and its default model. The lookup mirrors wireAIEmbedding's
// fallback chain (EmbeddingProvider → DefaultProvider, EmbeddingModel →
// per-provider default → AI default) so the demo and the wider semantic
// search use the same provider/model pair without extra config.
func (s *Server) resolveMoviesEmbeddingProvider() (ai.EmbeddingProvider, string, bool) {
	if s.aiRegistry == nil {
		return nil, "", false
	}
	name := strings.TrimSpace(s.cfg.AI.EmbeddingProvider)
	if name == "" {
		name = strings.TrimSpace(s.cfg.AI.DefaultProvider)
	}
	if name == "" {
		return nil, "", false
	}
	p, err := s.aiRegistry.Get(name)
	if err != nil {
		return nil, "", false
	}
	ep, ok := p.(ai.EmbeddingProvider)
	if !ok {
		return nil, "", false
	}
	model := strings.TrimSpace(s.cfg.AI.EmbeddingModel)
	if model == "" {
		if pc, exists := s.cfg.AI.Providers[name]; exists && pc.DefaultModel != "" {
			model = pc.DefaultModel
		} else {
			model = s.cfg.AI.DefaultModel
		}
	}
	return ep, model, true
}

// fitEmbedding truncates or zero-pads a vector to the schema's fixed
// dimension. Stage 2 uses VECTOR(3); real provider embeddings are much
// longer and would be rejected by the column type if passed verbatim.
// Adjustment happens here (not in the SQL) so that the demo schema can
// stay a faithful Stage 2 artifact while still accepting any provider.
func fitEmbedding(in []float64, dim int) []float64 {
	out := make([]float64, dim)
	n := len(in)
	if n > dim {
		n = dim
	}
	copy(out, in[:n])
	return out
}
