package pgmanager

import (
	"context"
	"fmt"
	"log/slog"
	"os"
	"os/exec"
	"path/filepath"
	"strings"

	"github.com/allyourbase/ayb/internal/sqlutil"
)

var openDatabaseClient = openPgxClient

const pgCtlStartLogName = "pg_ctl_start.log"

func writePostgresConf(dataDir string, port uint32, runtimeDir string, sharedPreloadLibraries []string) error {
	var buf strings.Builder
	buf.WriteString("# Generated by AYB managed Postgres\n")
	buf.WriteString("listen_addresses = '127.0.0.1'\n")
	fmt.Fprintf(&buf, "port = %d\n", port)

	if len(sharedPreloadLibraries) > 0 {
		fmt.Fprintf(&buf, "shared_preload_libraries = '%s'\n", strings.Join(sharedPreloadLibraries, ","))
	}
	if managedExtensionNameListContains(sharedPreloadLibraries, "pg_cron") {
		fmt.Fprintf(&buf, "cron.database_name = '%s'\n", dbName)
	}

	fmt.Fprintf(&buf, "unix_socket_directories = '%s'\n", runtimeDir)
	buf.WriteString("logging_collector = off\n")

	confPath := filepath.Join(dataDir, "postgresql.conf")
	return os.WriteFile(confPath, []byte(buf.String()), 0o644)
}

// runInitDB initializes a new data directory if it doesn't already exist.
// It checks for PG_VERSION to determine if initdb has already run.
func runInitDB(ctx context.Context, binDir, dataDir string, logger *slog.Logger) error {
	versionFile := filepath.Join(dataDir, "PG_VERSION")
	if _, err := os.Stat(versionFile); err == nil {
		logger.Debug("data directory already initialized, skipping initdb", "data_dir", dataDir)
		return nil
	}

	initdbBin := filepath.Join(binDir, "bin", "initdb")
	cmd := exec.CommandContext(ctx, initdbBin,
		"-D", dataDir,
		"-U", dbUser,
		"--auth=trust",
		"--encoding=UTF8",
		"--locale=C",
	)
	cmd.Stdout = newLogWriter(logger)
	cmd.Stderr = newLogWriter(logger)

	logger.Info("initializing postgres data directory", "data_dir", dataDir)
	if err := cmd.Run(); err != nil {
		return fmt.Errorf("initdb failed: %w", err)
	}
	return nil
}

func openPgCtlStartLog(dataDir string) (*os.File, error) {
	logPath := filepath.Join(dataDir, pgCtlStartLogName)
	logFile, err := os.OpenFile(logPath, os.O_CREATE|os.O_WRONLY|os.O_APPEND, 0o644)
	if err != nil {
		return nil, fmt.Errorf("opening pg_ctl start log %s: %w", logPath, err)
	}
	return logFile, nil
}

// startPostgres starts the postgres server using pg_ctl.
func startPostgres(ctx context.Context, binDir, dataDir string, port uint32, logger *slog.Logger) error {
	logFile, err := openPgCtlStartLog(dataDir)
	if err != nil {
		return err
	}
	defer logFile.Close()

	pgctlBin := filepath.Join(binDir, "bin", "pg_ctl")
	cmd := exec.CommandContext(ctx, pgctlBin,
		"start",
		"-D", dataDir,
		"-l", logFile.Name(),
		"-w",
		"-t", "60",
		"-o", fmt.Sprintf("-p %d", port),
	)
	cmd.Stdout = logFile
	cmd.Stderr = logFile

	logger.Info("starting postgres", "port", port, "data_dir", dataDir, "log_file", logFile.Name())
	if err := cmd.Run(); err != nil {
		return fmt.Errorf("pg_ctl start failed: %w", err)
	}
	return nil
}

// stopPostgres stops the postgres server using pg_ctl fast mode.
func stopPostgres(binDir, dataDir string, logger *slog.Logger) error {
	pgctlBin := filepath.Join(binDir, "bin", "pg_ctl")
	cmd := exec.Command(pgctlBin,
		"stop",
		"-D", dataDir,
		"-m", "fast",
		"-w",
		"-t", "30",
	)
	cmd.Stdout = newLogWriter(logger)
	cmd.Stderr = newLogWriter(logger)

	logger.Info("stopping postgres", "data_dir", dataDir)
	if err := cmd.Run(); err != nil {
		return fmt.Errorf("pg_ctl stop failed: %w", err)
	}
	return nil
}

// ensureManagedDatabase connects to the default "postgres" database and idempotently
// creates the managed AYB database if it does not already exist.
func ensureManagedDatabase(ctx context.Context, port uint32, logger *slog.Logger) error {
	db, err := openDatabaseClient(ctx, managedConnURL(port, "postgres"))
	if err != nil {
		return fmt.Errorf("connecting to postgres database: %w", err)
	}
	defer db.Close()

	var exists bool
	if err := db.QueryRowContext(ctx, "SELECT EXISTS (SELECT 1 FROM pg_database WHERE datname = $1)", dbName).Scan(&exists); err != nil {
		return fmt.Errorf("checking for database %s: %w", dbName, err)
	}
	if exists {
		return nil
	}

	logger.Info("creating managed postgres database", "database", dbName, "port", port)
	if _, err := db.ExecContext(ctx, "CREATE DATABASE "+sqlutil.QuoteIdent(dbName)); err != nil {
		return fmt.Errorf("creating database %s: %w", dbName, err)
	}
	return nil
}

func initExtensions(ctx context.Context, connURL string, extensions []string, logger *slog.Logger) error {
	if len(extensions) == 0 {
		return nil
	}

	db, err := openPgx(ctx, connURL)
	if err != nil {
		return fmt.Errorf("connecting for extension init: %w", err)
	}
	defer db.Close()

	// Query available extensions.
	available := make(map[string]bool)
	rows, err := db.QueryContext(ctx, "SELECT name FROM pg_available_extensions")
	if err != nil {
		return fmt.Errorf("querying pg_available_extensions: %w", err)
	}
	defer rows.Close()
	for rows.Next() {
		var name string
		if err := rows.Scan(&name); err != nil {
			return fmt.Errorf("scanning extension name: %w", err)
		}
		available[name] = true
	}
	if err := rows.Err(); err != nil {
		return fmt.Errorf("iterating pg_available_extensions: %w", err)
	}

	for _, ext := range extensions {
		dbExt := managedExtensionName(ext)
		if !available[dbExt] {
			logger.Warn("extension not available in this PostgreSQL installation — "+
				"connect to an external PostgreSQL with the extension installed, "+
				"or verify the managed PG build includes it",
				"extension", ext)
			continue
		}
		// Extension names are from our config, not user input, so safe to interpolate.
		_, err := db.ExecContext(ctx, "CREATE EXTENSION IF NOT EXISTS "+sqlutil.QuoteIdent(dbExt))
		if err != nil {
			return fmt.Errorf("creating extension %s: %w", ext, err)
		}
		logger.Info("extension initialized", "extension", ext)
	}

	return nil
}

func managedExtensionName(ext string) string {
	switch strings.TrimSpace(strings.ToLower(ext)) {
	case "pgvector", "vector":
		return "vector"
	default:
		return strings.TrimSpace(ext)
	}
}

func managedExtensionNameListContains(values []string, want string) bool {
	for _, value := range values {
		if managedExtensionName(value) == want {
			return true
		}
	}
	return false
}
